name: image
version: 2.1.2
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides server and web apps the ability to load, manipulate, and save images with various image file formats including PNG, JPEG, GIF, WebP, TIFF, TGA, PSD, PVR, and OpenEXR.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/wiki
environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'
dependencies:
  archive: '>=1.0.16 <3.0.0'
  xml: '>=3.2.5 <4.0.0'
dev_dependencies:
  test: '>=0.12.42 <2.0.0'
  pedantic: ^1.0.0
  build_web_compilers: '>=0.3.6 <2.0.0'
  build_runner: '>=1.3.0 <2.0.0'
