name: image
version: 4.5.5
description: >-
  Dart Image Library provides server and web apps the ability to load, manipulate,
  and save images with various image file formats.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/blob/main/doc/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  meta: ^1.17.0
  xml: ^6.6.1

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  http: ^1.1.0
  lints: ^6.0.0
  test: ^1.28.0
  web: ^1.1.1
