name: image
version: 2.0.5
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides server and web apps the ability to load, manipulate, and save images with various image file formats including PNG, JPEG, GIF, WebP, TIFF, TGA, PSD, PVR, and OpenEXR.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/wiki
environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'
dependencies:
  archive: '>=1.0.16 <3.0.0'
  xml: '>=2.0.0 <4.0.0'
dev_dependencies:
  test: '>=0.12.42 <2.0.0'
