name: image
version: 3.0.6
description: >-
  Provides server and web apps the ability to load, manipulate, and save images
  with various image file formats including PNG, JPEG, GIF, BMP, WebP, TIFF,
  TGA, PSD, PVR, and OpenEXR.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/wiki

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  archive: ^3.0.0
  meta: ^1.3.0
  xml: ^5.0.0

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_web_compilers: ^2.16.1
  pedantic: ^1.10.0
  test: ^1.16.0
